/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressesForm: typeof import('./src/components/forms/AddressesForm.vue')['default']
    AddressesItem: typeof import('./src/components/items/AddressesItem.vue')['default']
    AffilationsForm: typeof import('./src/components/forms/AffilationsForm.vue')['default']
    AffilationsItem: typeof import('./src/components/items/AffilationsItem.vue')['default']
    ChecksForm: typeof import('./src/components/forms/ChecksForm.vue')['default']
    ChecksItem: typeof import('./src/components/items/ChecksItem.vue')['default']
    ContactsForm: typeof import('./src/components/forms/ContactsForm.vue')['default']
    ContactsItem: typeof import('./src/components/items/ContactsItem.vue')['default']
    DivMenu: typeof import('./src/components/element/DivMenu.vue')['default']
    DocumentsForm: typeof import('./src/components/forms/DocumentsForm.vue')['default']
    DocumentsItem: typeof import('./src/components/items/DocumentsItem.vue')['default']
    EducationsForm: typeof import('./src/components/forms/EducationsForm.vue')['default']
    EducationsItem: typeof import('./src/components/items/EducationsItem.vue')['default']
    InquiriesForm: typeof import('./src/components/forms/InquiriesForm.vue')['default']
    InquiriesItem: typeof import('./src/components/items/InquiriesItem.vue')['default']
    InvestigationsForm: typeof import('./src/components/forms/InvestigationsForm.vue')['default']
    InvestigationsItem: typeof import('./src/components/items/InvestigationsItem.vue')['default']
    ItemView: typeof import('./src/components/content/ItemView.vue')['default']
    LabelValue: typeof import('./src/components/element/LabelValue.vue')['default']
    LayoutView: typeof import('./src/components/content/LayoutView.vue')['default']
    PersonDiv: typeof import('./src/components/items/PersonDiv.vue')['default']
    PersonView: typeof import('./src/components/content/PersonView.vue')['default']
    PoligrafsForm: typeof import('./src/components/forms/PoligrafsForm.vue')['default']
    PoligrafsItem: typeof import('./src/components/items/PoligrafsItem.vue')['default']
    PreviousForm: typeof import('./src/components/forms/PreviousForm.vue')['default']
    PreviousItem: typeof import('./src/components/items/PreviousItem.vue')['default']
    ResumeForm: typeof import('./src/components/forms/ResumeForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffsForm: typeof import('./src/components/forms/StaffsForm.vue')['default']
    StaffsItem: typeof import('./src/components/items/StaffsItem.vue')['default']
    TabsView: typeof import('./src/components/content/TabsView.vue')['default']
    UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEmpty: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UError: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Error.vue')['default']
    UFooter: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPage: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WorkplacesForm: typeof import('./src/components/forms/WorkplacesForm.vue')['default']
    WorkplacesItem: typeof import('./src/components/items/WorkplacesItem.vue')['default']
  }
}
